### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by lethosor**

### CODE REVIEW

**Comment by BenLubar** [comment]
@lethosor was this intentionally submitted? It looks like an example.

**Comment by lethosor** [comment]
Kind of. Couldn't get it to generate a config without opening a PR. I do intend to get this working eventually (replacing Travis) but haven't gotten around to it yet.

**Comment by BenLubar** [comment]
We could also put it in BuildMaster

**Comment by lethosor** [comment]
We could. I'm leaning towards this as more of a Travis replacement because it has some nicer features compared to Travis, including more Github-friendly output in the 'checks' tab (so people don't have to filter through the logs, which can get confusing for those unfamiliar with them). I'd like to have some quick standalone CI (Buildmaster can have a slow turnaround time when it's busy building DFHack+plugins) so people get test results back quickly. I'm experimenting on this project first since it's not very active. We also don't currently distribute standalone clsocket binaries, so we probably don't need the cross-platform support that Buildmaster provides (although it's definitely worth keeping in mind, and I won't stop you from setting it up).

**Comment by lethosor** [comment]
Closing in favor of GitHub Actions

**Pull request closed without merging**
